### ISSUE TITLE
Add function for assessing presences of propclass and/or auxclass for record

### ISSUE THREAD

**Issue by Djvogel03** [WIStCart/ParcelValidationTool#12]
Add function that ensure value in auxclass or propclass for all "true" parcels (with valid parcelid).  Need to consider TAXROLLYEAR value in function (needs to be expected or past, as future years won't have prop/aux values yet).

-Can also include the current functions that are looking for duplicate values in propclass and auxclass within this function.

**Comment by codiesee** [comment]
Before closing, make sure to check that the function works as expected on \<Null> parcelid values
