### ISSUE TITLE
Integrate “Explain/Certify” section into tool

### ISSUE THREAD

**Issue by codiesee** [WIStCart/ParcelValidationTool#14]
Integration of “Explain/Certify” section into tool, rather than requiring a separate text file input. Lets look into the best way to implement this so that submitter have fewer random files to deal with. This will be valuable so that the submission of this information is more intuitive, and harder to mess-up.

**Comment by Djvogel03** [comment]
I'm having trouble finding a way to make a 'text input' field for this more of a block / text box as opposed to just one giant string line (which I really don't think would work).  We could just make the field where they input the file required as opposed to optional to prevent a person from being able to submit unless they have input the file...

Thoughts?

Directives:
1) Make the Explain Certify .txt path is required.
2) Possibly, double check that the uploaded .txt contains some added characters or lines.
