### ISSUE TITLE
Include "Mixed Type" Condo Modeling Option in Tool

### ISSUE THREAD

**Issue by codiesee** [WIStCart/ParcelValidationTool#20]
Mixed type condo modeling: Some counties practice mixed type condo modeling. It appears that at least Iowa County is confirmed to follow this practice, they have predominantly Type #1–Discrete but also practice Type #2, as determined by the project team’s observations.

**Recommendation**: This condition was accepted as valid for V3 submission as there are no reason that this condition would degrade the value of the statewide layer. The project team should provide documentation that supports this concept and informs submitter that it is acceptable. **The project team
should also provide an option in the Submission Form for "Mixed type condo modeling #1-4.**"

**Comment by Djvogel03** [comment]
Removed 'Relational Model (1:M)' and replaced with 'Condo Type #5 - Mixed Modeling'
