### ISSUE TITLE
Ensure <Null> values in all cases where an IMPVALUE does not exist

### ISSUE THREAD

**Issue by codiesee** [WIStCart/ParcelValidationTool#21]
Ensure \<Null> values in all cases where an IMPVALUE does not exist: It appears that a few counties have provided \<Null> values in all cases where an IMPVALUE does not exist. The majority of the data contributors provide a value 0 instead of \<Null>, which indicates that there is no
improvement, whereas \<Null> would indicate there is missing or no data. This practice adds a level of
granularity and value to the data.

**Recommendation**:  This precedent is expected to be adopted but currently pending discussion w/ DOA.  It could be enforced through the Validation and Submission Tool but the exact logic for implementing this is not researched yet.

It would be valuable to:
- Take a look at the V3 parcel layer (D: but keep in mind that statewide logic will have changed any "" strings or 0 values to \<Null>) 
- Take a look at the V3 OneNote (D: but keep in mind that this issue shouldnt show up since all tat was done was check to ensure the field only included the 3 appropriate domains.) 
- We'll need to figure out a way to isolate this type of condition (where IMPVALUE = 0) so that logic can be built. 
- D: looking at the final V3 parcel layer, we do have a number of records where CNTASSDVALUE is populated, but LNDVALUE and IMPVALUE are both populated as \<Null>
- D: I will look at Portage County's data, b/c I know on first submission they had a good illustration of the issue.

**Comment by Djvogel03** [comment]
Some stats from research of the V3 Layer:

CNTASSDVALUE <> NULL & IMPVALUE IS NULL  -- 46746 Records
(Waukesha, Dodge, Clark, Polk, Brown)
*IMPROVED is NULL for all
*4985 w/ CNTASSDVALUE = 0
So, **41,761** Records (w/ '0' records removed)

CNTASSDVALUE <> NULL & (LNDVALUE & IMPVALUE = NULL) -- 17164 Records
(Waukesha, Polk, few Dodge & Ozaukee)
*4985 w/ CNTASSDVALUE = 0
So, **12,179** Records (w/ '0' records removed)

This is a tough one to tackle b/c we don't know how it comes out of the county's taxroll system and can expect that it will vary from one county to the next...

Some Proposed Options

1) Calculate IMPROVED in statewide logic and disregard values submitted

2) Check CNTASSDVALUE (if populated) ensure that LNDVALUE and/or IMPVALUE is either populated w/ true number or has '0'(no NULL allowed) - this would solve calc of IMPROVED issues observed

3) Integrate 'Address Completeness' rating and for all records w/ highest score (complete site address), use that to compare/calc improved??  (Could work, but could also pose challenges...)

---> At the current time, I'm leaning towards option 2

**Comment by codiesee** [comment]
As per 12/12/17 meeting with D, will check logic to ensure that bi-directional testing works. 

- **_YES_** if IMPVALUE is > $0
- **_NO_** if IMPVALUE is = $0
- **_\<Null>_** if IMPVALUE is \<Null>

If the function correctly tests for these conditions, leave function as-is.

**Comment by codiesee** [comment]
Validated against dummy data, the above logic is flagged as appropriate in all test scenarios. Will add note to documentation for the error message "Value provided in IMPROVED doesnt correspond with IMPVALUE for this record - please verify." instructing the user how to verify.
