### ISSUE TITLE
Add logic to clear error fields if fields exist in input dataset

### ISSUE THREAD

**Issue by codiesee** [WIStCart/ParcelValidationTool#23]
It appears that **_if_** an output dataset from a previous execution of the tool is used as the input to a subsequent execution of the tool then the error messages written to the error fields will not be overwritten unless a new error happens on the row. 

- We should write logic to clear the error fields if the fields (GeneralElementErrors, AddressElementErrors, TaxElementErrors, GeometricElementErrors) exist in the input dataset.

- We could do this by deleting and re-adding the fields each time the tool is run or by making sure that \<Null> is written to the fields when no error flag is found.

**Comment by Djvogel03** [comment]
This shouldn't be the case, but I could have screwed something up when I moved the schema check into a function.  When the schema check is called, it should delete the error fields if they exist.

**Comment by codiesee** [comment]
Workflow for reproducing the issue:

1. Execute the tool on the test data under TEST mode
2. Using the resulting FC in ArcMap, calculate some dummy text into the 4 error fields (on all records)
3. Run the tool again using the output FC (the FC containing the error fields calculated with dummy text).
*The result has been a mix of the dummy text and valid errors 
![untitled](https://user-images.githubusercontent.com/7830695/33436775-94e62e46-d5ab-11e7-8812-43258860bc6c.png)

*This issue does not appear to happen on the original (V3) tool.
