### ISSUE TITLE
FINAL Mode and Output of Final Feature Class

### ISSUE THREAD

**Issue by codiesee** [WIStCart/ParcelValidationTool#41]
Some users might overlook the fact that the validation tool run in final mode doesn’t populate an output feature class like test mode does. FINAL mode will result in an .ini file with all the information but no feature class is produced. This isn't an error but something we could think about better documenting or approaching in a different manner for V5.

**Comment by Djvogel03** [comment]
We had 7-10 counties that submitted the fgdb w/o including the actual parcel feature class.  We assume this was b/c they thought the final fun out the tool copied the fc they input into the fgdb output they populated.  To resolve, the tool parameters for Output Directory, Output Feature Class Name and Output Validation Summary Directory are now grayed out and do not take input when run in Final Mode.
