### ISSUE TITLE
Message for Geometry Check 

### ISSUE THREAD

**Issue by codiesee** [WIStCart/ParcelValidationTool#42]
Make the message for a failing geometry check more obvious in the output summary in TEST mode. Also, make sure that it either prevents the .ini from being created or is clearly output as a message when running in FINAL mode

**Comment by AnaJWells** [comment]
The functions that check geometry quality are working. Message hasn't change, but it will be change in the summary document.

**Comment by AnaJWells** [comment]
Still working
