### ISSUE TITLE
Validation tool will not trigger a geometric shift flag

### ISSUE THREAD

**Issue by codiesee** [WIStCart/ParcelValidationTool#43]
Under certain circumstances validation tool will not trigger a geometric shift flag and an error will not show up in the .ini as a geometric error of 1 (even if there is a shift in all of the parcels). Walworth County was an example for V4.  This failure to report a geometric issue happens because the function is configured to bail-out if the query against LTSB returns nothing for all 10 checks (e.g. the pin has changed) or if there is a failure in the query or the geometry checking logic (e.g. the geometry is corrupt).  Also, if none of the 10 checks were validated a geometric error will still not be counted...  We chose to let this pass deliberately for V4 because the flip side could cause confusion (i.e. counties looking for geometric issues that don't exist).

something like the below changes could be implemented as a fix (these were un-vetted tests and should be scrutinized)

![image](https://user-images.githubusercontent.com/7830695/45049747-300a1800-b045-11e8-949e-ef5f94e52665.png)

**Comment by AnaJWells** [comment]
Validation tool now triggers when there is a geometric shift like in Walworth County
