### ISSUE TITLE
Integrate commit to V4ValidationTool_dist with main codebase

### ISSUE THREAD

**Issue by codiesee** [WIStCart/ParcelValidationTool#56]
The commit to:
        ParcelValidationTool/V4ValidationTool_dist/script/Summary.py
... Should actually be made to:
        ParcelValidationTool/script/Summary.py
Sorry we did not mention that these two _dis files (V3ValidationTool_dist and V4ValidationTool_dist) are archives of past distributables.  Undoing the changes to V4ValidationTool_dist and integrating the changes with  ParcelValidationTool/script/Summary.py would be optimal.

CID: 
(727d6ca)  
(727d6ca0ee2c33609b2058393e2269cfbb788a9b)

**Comment by claytongroth** [comment]
Updated. The original Summary.py from V4 was restored and the new one added to ParcelValidationTool/script/Summary.py
