### ISSUE TITLE
For Dec 5th: Produce a list of Validation Tool Improvements/Edits

### ISSUE THREAD

**Issue by codiesee** [WIStCart/ParcelValidationTool#58]
For Dec 5th: Produce a list of Validation Tool Improvements/Edits. 

This list will be used for discussion on Dec 6th meeting and should be valuable in scoping the amount of documentation rewriting that will be needed before call for data.

**Comment by codiesee** [comment]
*the list should include all complete and targeted improvements/edits.

**Comment by Djvogel03** [comment]
Starting List:

1. **Update UNITID and UNITTYPE check message** (Completed) _**- Flag message created**_
    > "The value in the UNITID/UNITTYPE does not appear to be in a list created from V4 data.  Please verify this value is appropriately placed in this field."

2. **Strengthen SCHOOLDIST field check function** (Completed) _**- No flag message alteration needed**_
    > The function now ensures that ' SCHOOL DISTRICT' is apart of the SCHOOLDIST value provided. In the past it just looked at the actual name.

3. **Update STREETNAME flag message to be more general** (Completed) _**- Flag message altered
     //In the documentation this was a associated with a generic message, although this is the only field it would have been thrown on, so I altered document to reflect the specific flag pointing to STREETNAME field (p13).**_
    > Updated message to "Value provided in STREETNAME does not appear in list created from V4 data.  Please verify this value contains only the STREETNAME."
    > Value provided is now compared against a county specific list as opposed to a list for the entire state.

4. **Function that checks all fields for coded domain values** (Completed) - **_Planned field names will be listed in 'BroadLevelErrors' if exist_**
    > Function added and if fields are identified, then they are added to a list.  If list is populated, fields will be listed in new summary.txt display method.

5. **Function that checks Zip4 field** (Completed) _**- Flag message created**_
    > Verifies that values are 4 digits in length.

6. **Check future taxrollyear records for tax data** (Completed) _**- Flag message created**_
    > Records with future taxrollyear values checked to ensure that impvalue, cntassvalue, improved, estfmkvalue, netvalue, grossvalue, propclass and auxclass are all <Null> as to be expected.

7. **Function that checks CNTASSDVALUE <> LNDVALUE if IMPVALUE > 0** (Completed) _**- I turned this function off for now, as it will throw false flags on counties that incorporate forestvalue into their total assessed...  Didn't think it was worth writing the complex logic to account for all of those cases for now.**_
    > The totCheck function checks to ensure that if impvalue > 0 that cntassdvalue != lndvalue.

8. **Update of AUXCLASS list to include new unusual values provided in V4** (Completed)

9. **Stylize current Summary.txt file in another format to be more readable and better alert users to potential issues observed w/in validated data** (Work in progress)
    > Exploring a different method for displaying this information to end users.  Current working idea, is to output a .json file that can then be consumed by mustache/handlebars template and display within users browser window.  Will allow us to color code and highlight significant errors / deficiencies observed. Also addresses the objective in Recommendation #1 (https://doa.wi.gov/DIR/V4_Final_Report.pdf) to Flag fields that are provided with <Null> values for the entire dataset when values are expected (e.g., ESTFMKVALUE is missing for all records in the submitted dataset).

10. **Validate checkGeometry function is working and if thrown, make message more forceful for end user** (Work in progress)  _**-This has been completed and the error message been integrated into the documentation.**_
    > Ensuring that this function is working correctly and considering making it prevent INI creation if issue is not resolved.  Ideally, this would have users resolve issue before submitting so we can reduce back and forth with county about issue and prevent expending excessive amounts of time on issue (i.e. Walworth issue from V4).  
    > Considering having some type of back door to disable if we do make function restrict INI creation for legitimate flag (e.g. integration of plss corners has resulted in more accurate parcel line drawing, but causing fail when trying to validate against V4 geoms).

11. **Create 2+ submission FGDBs in which all layers intended for submission will be popualted** (Concept)
    > Numerous counties submitted last year without ensuring that the feature class they have validated existed in the FGDB they were sending.  In final mode, we could create the Parcels and OtherLayers FGDBs and then copy the feature classes mapped within the tool during final run into said DBs.  These would then be the FGDBs the county would include in the zipped file submitted to LTSB.
    > Could be some drawbacks to this including:
        - Some counties provided more "otherLayers" than just what is mapped in the tool during final run
        - Could cause confusion for those counties that submitted correctly in years past
        - Others??

12. **Validate Explain/Certify.txt file is thoroughly filled out** (Concept - Low Priority)
    > This was based off feedback from Ian Grasshof.  We have not pursued other methods for validating this information aside from what was done in V4 submission tool as of now...

13. **Numerous data files to update for V5 tool** (Work in progress)
    > A number of ancillary data files are used for comparing submitted values vs V4 values.  Some files need to be updated as necessary (new streettype values added, taxrollyears versioned up, VERSION.txt file updated, etc.
    >This is most often done as one of the final steps to allow testing of tool/functions with V4 data to prevent throwing for improper flags b/c of incorrect taxrollyear, tool version, domain lists, etc...

14. **Adjust Final Mode Searchable Inputs Parameters** (Completed)
    > To take some of the ambiguity out of the final run and counties (7-10?) submitting the fgdb without including the parcel feature class, we grayed out the Output Directory, Output Feature Class Name and Output Validation Summary Directory.  Hopefully this will help remove some of the issues with missing data at submission.

15. **Update to Geometry Check function to ensure executing properly** (Completed) 
    > The check geom function didn't seem to be catching issues that it should have been.  Issue was resolved and now in tests throws broad level flag/error where it should.  Considering making this flag/error an INI deal breaker, but need to determine a backdoor option that would allow counties to create INI if say parcels geoms were improved, etc.

16. **Update to the school_district_codes.csv** (Completed)
    > Changes include 2 district name changes (DURAND SCHOOL DISTRICT to DURAND-ARKANSAW SCHOOL DISTRICT and SENECA SCHOOL DISTRICT to SENECA AREA SCHOOL DISTRICT), 2 district removals (RICHFIELD J1 SCHOOL DISTRICT and FRIESS LAKE SCHOOL DISTRICT were removed). Also, changed the distributed .xlsx file available here: https://www.sco.wisc.edu/parcels/Submission/ to reflect the same changes.
