### ISSUE TITLE
Updates to Validation Tool Data

### ISSUE THREAD

**Issue by Djvogel03** [WIStCart/ParcelValidationTool#71]
- [x] School_district_codes.csv
- [x] V6_PinSkips.txt
- [x] V6_PrefixDomains_Simplified.txt  //no updates
- [x] V6_StreetType_Simplified.txt
- [x] V6_SuffixDomains_Simplified.txt
- [x] V6_TaxRollYears.txt
- [x] V6_UnitId_Simplified.txt
- [x] V6_UnitType_Simplified.txt

**Comment by TKaz84** [comment]
Is this actually done?

**Comment by Djvogel03** [comment]
Based on the updates of the naming conventions for each of the files I was assuming so.  You double-checked the school_district_codes right?  CoNameFips & LSAD_Simplified won't change.  Do you want to check off all the ones in the list that you updated/checked?

**Comment by AnaJWells** [comment]
I updated all the data except for pinskips and school_district_codes.  Are the prefixes not updated? I can check again

**Comment by Djvogel03** [comment]
@AnaJWells @TKaz84  Prefixes generally don't change and I think we have every allowable possibility in the current text file.  I think pinskips and school_district_codes were done by Tom.  In which case, all would be complete on this list.

**Comment by AnaJWells** [comment]
That's right. I checked and change only the label of the file.  I am not sure why it has "// no updates" ...  Then this issue should be closed.

**Comment by Djvogel03** [comment]
I think I put that in last year to remind me/us that this file didn't have to or shouldn't be updated.  I will mark this issue as completed and close it.
