### ISSUE TITLE
Update TEST_DATASET_PARCELS_2021

### ISSUE THREAD

**Issue by Djvogel03** [WIStCart/ParcelValidationTool#89]
-Need to update TAXROLLYEAR values to coincide with V7 expected values
-Any others?

**Comment by Djvogel03** [comment]
@TKaz84 I copied last year's test dataset and placed it in the V7ValidationTool_dist directory.  I updated the names (the directory and the FGDB name, but didn't go into the feature class at all.

**Comment by TKaz84** [comment]
Done
