### ISSUE TITLE
Flag records containing an incomplete PSTLADRESS

### ISSUE THREAD

**Issue by codiesee** [WIStCart/ParcelValidationTool#9]
Occasionally, records will be found within submitted parcel data that contain some portions of an address within PSTLADRESS but are not complete enough to be a usable complete address.

Validation tool should have logic added to it that enables the tool to flag PSTLADRESS values that
are not only <Null> but also those populated with an incomplete address. Examples of this issue are as such:

- CITY, STATE, ZIP  (enter <Null> instead)
- GILMAN, WI, 54433 (enter <Null> instead)

**Comment by codiesee** [comment]
*Testing was performed over the tool as of 0c55dbaf40ee9cde6a6ca46b03606d53130d09bb (BS's last commit on 12/13/17). Note that this function caught many incomplete addresses over the V3 data (which was cleaned to a great degree already, so that's great!). Here are some observations.

**For improving the function:**
1) We should focus on continued flagging of items similar to the first list, and exclusion of flagging on items similar to those in the second list. 
2) We should pose flags from this function as "passive" meaning that they are up to the submitter's discretion whether to include the address, modify the address, or \<Null> the address.

**These are examples of successfully caught incomplete addresses:**
WI
WAUPUN, WI  53963
WASHINGTON ISLAND WI 54246
VACANT, SUPERIOR, WI  54880
UNKNOWN, UNITY, WI, 54488
TOWN HALL
SUPERIOR, WI  54880
STURGEON BAY WI 54235
ROSIERE WI
ROADS, GORDON, WI  54838
RHINELANDER WI 54501
POST NO 42,,,00000
POPPLE RIVER WI 54542
PENINSULA STATE PARK   ??
NONE, DULUTH, MN  55803
NONE, MAPLE, WI  54854
MT CALVARY, WI  53057
N FOND DU LAC, WI  54937
N WASHINGTON ST, THORP, WI, 54771
MADISON WI 53701
LAONA WI 54541
HWY32/55 ARGONNE WI 54511
HIGHWAY 105, SUPERIOR, WI  54880
HAMILTON ONTARIO CAN, L H K
GREENLEAF WI 54126
GRANT, GRANTON, WI, 54436
GIBRALTAR   ??
FORESTVILLE WI 54213
EGG HARBOR WI 54209
DNR PEWAUKEE WI 53702
DENMARK WI 54208
CRANDON WI 54520
COTHERN ST,MINERAL POINT,WI,53565
CONSERVATION COMM PEWAUKEE WI 53702
ARGONNE WI 54511

**False flags are being thrown on some of the following examples, we can use this as a test list:**
P.O. BOX 39, ODANAH, WI, 54861
% ALAN BATTERMAN, 869 DURWARD ST, CHULA VISTA , CA  919106406
% CITY CLERK, P O BOX 150, FOND DU LAC, WI  549360150
% D HANK HECHIMOVICH, W4438 WOODWARD RD, HORICON, WI  53032
% FERRELLGAS INC  ONE LIBERTY PLAZA  LIBERTY MO 64068
%GERALD F & JANICE K MICKE, W11032 CTY HWY N, STANLEY, WI, 54768
(LAND FILL)  421 NEBRASKA ST  STURGEON BAY WI 54235
100 W STH 16, RIO, WI  539600000
1183 HOMESTEAD DRIVE, SUN PRAIRIE, WI  535900000
1919 WALLINFORD CR, SUN PRAIRIE, WI  535900000
3100 HARTFORD ST N CONDO 229, ST PETERSBURG, FL 33713-2441
4119 SECOND LANE, BRIGGSVILLE, WI  539200000
A GEORGE & ALGRETA A SCHUTTE, TRUSTEES, W6608 SMOCK VALLEY RD, MONROE, WI 53566
APT #D-304  5600 MOCKINGBIRD LN  GREENDALE WI 53129
ATTN BLM EASTERN STATES 7450 BOSTON BLVD, SPRINGFIELD, VA 22153
ATTN: ACCOUNTS PAYABLE, 22575 STATE HWY 6 SOUTH, NAVASOTA, TX  77868
BRUGGER TRUST, 940 S PARK AVE, FOND DU LAC, WI  54935
BLDG 4 APT 154  911 GARDENIA  DELRAY BEACH FL 33483
C/O ALEXANDER KRUEGER  N9434 CEMETERY RD  BRILLION WI 54110
C/O LITTLE SWEDEN  8984 STATE HIGHWAY 42  FISH CREEK WI 54212
CARTER MACHINE WORKS, 1217 12TH AVE, MONROE, WI 53566
CITY BOX, CHETEK, WI 54728
ESJ TOWERS UNIT 776 6165 ISLA VERDE AVE, CAROLINA, PR 00979
N2151 COUNTY ROAD C, RIO, WI  539600000
N949 CTH N, RIO, WI  539600000
P O BOX 100, LOMIRA, WI  53048
P.O. BOX 111, GLIDDEN, WI, 54527
POBOX 1105, EAGLE RIVER, WI 54521
PO BX 4900, SCOTTSDALE AZ  85261\
PO  BOX 930307, VERONA WI  53593
ROUTE 1 BOX 1201 , HARDIN, MT 59034
RT 1 BOX 216, SUPERIOR, WI  54880
SUITE A  20711 WATERTOWN PLANK RD  WAUKESHA WI 53186-1881
UNIT 104  4620 TURNBERRY LAKE DR  ESTERO FL 33928-6984
W2908 LONG CROSSING ROAD, RIO, WI  539600000

**Comment by Djvogel03** [comment]
I think we may need to scrap this function.  I've been checking a number of the records it has flagged against the county tax information websites and the addresses provided in the parcel layer are the same addresses provided on the tax roll bills.  I'm not sure how we can intelligently differentiate between addresses missing components and the addresses that the counties have.  Any thoughts?
